/* soapClient.c
   Generated by gSOAP 2.8.130 for blackJack.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.130 2023-11-22 22:53:17 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_blackJackns__register(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct tMessage playerName, int *result)
{	if (soap_send_blackJackns__register(soap, soap_endpoint, soap_action, playerName) || soap_recv_blackJackns__register(soap, result))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_blackJackns__register(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct tMessage playerName)
{	struct blackJackns__register soap_tmp_blackJackns__register;
	if (soap_endpoint == NULL)
		soap_endpoint = "http//localhost:10000";
	soap_tmp_blackJackns__register.playerName = playerName;
	soap_begin(soap);
	soap->encodingStyle = ""; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_blackJackns__register(soap, &soap_tmp_blackJackns__register);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_blackJackns__register(soap, &soap_tmp_blackJackns__register, "blackJackns:register", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_blackJackns__register(soap, &soap_tmp_blackJackns__register, "blackJackns:register", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_blackJackns__register(struct soap *soap, int *result)
{
	struct blackJackns__registerResponse *soap_tmp_blackJackns__registerResponse;
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_blackJackns__registerResponse = soap_get_blackJackns__registerResponse(soap, NULL, "", NULL);
	if (!soap_tmp_blackJackns__registerResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_blackJackns__registerResponse->result)
		*result = *soap_tmp_blackJackns__registerResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_blackJackns__getStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, int gameId, struct tMessage playerName, struct tBlock *block)
{	if (soap_send_blackJackns__getStatus(soap, soap_endpoint, soap_action, gameId, playerName) || soap_recv_blackJackns__getStatus(soap, block))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_blackJackns__getStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, int gameId, struct tMessage playerName)
{	struct blackJackns__getStatus soap_tmp_blackJackns__getStatus;
	if (soap_endpoint == NULL)
		soap_endpoint = "http//localhost:10000";
	soap_tmp_blackJackns__getStatus.gameId = gameId;
	soap_tmp_blackJackns__getStatus.playerName = playerName;
	soap_begin(soap);
	soap->encodingStyle = ""; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_blackJackns__getStatus(soap, &soap_tmp_blackJackns__getStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_blackJackns__getStatus(soap, &soap_tmp_blackJackns__getStatus, "blackJackns:getStatus", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_blackJackns__getStatus(soap, &soap_tmp_blackJackns__getStatus, "blackJackns:getStatus", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_blackJackns__getStatus(struct soap *soap, struct tBlock *block)
{
	struct blackJackns__getStatusResponse *soap_tmp_blackJackns__getStatusResponse;
	if (!block)
		return soap_closesock(soap);
	soap_default_blackJackns__tBlock(soap, block);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_blackJackns__getStatusResponse = soap_get_blackJackns__getStatusResponse(soap, NULL, "", NULL);
	if (!soap_tmp_blackJackns__getStatusResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (block && soap_tmp_blackJackns__getStatusResponse->block)
		*block = *soap_tmp_blackJackns__getStatusResponse->block;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_blackJackns__play(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct tMessage playerName, int gameId, unsigned int playerMove, int *code)
{	if (soap_send_blackJackns__play(soap, soap_endpoint, soap_action, playerName, gameId, playerMove) || soap_recv_blackJackns__play(soap, code))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_blackJackns__play(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct tMessage playerName, int gameId, unsigned int playerMove)
{	struct blackJackns__play soap_tmp_blackJackns__play;
	if (soap_endpoint == NULL)
		soap_endpoint = "http//localhost:10000";
	soap_tmp_blackJackns__play.playerName = playerName;
	soap_tmp_blackJackns__play.gameId = gameId;
	soap_tmp_blackJackns__play.playerMove = playerMove;
	soap_begin(soap);
	soap->encodingStyle = ""; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_blackJackns__play(soap, &soap_tmp_blackJackns__play);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_blackJackns__play(soap, &soap_tmp_blackJackns__play, "blackJackns:play", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_blackJackns__play(soap, &soap_tmp_blackJackns__play, "blackJackns:play", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_blackJackns__play(struct soap *soap, int *code)
{
	struct blackJackns__playResponse *soap_tmp_blackJackns__playResponse;
	if (!code)
		return soap_closesock(soap);
	soap_default_int(soap, code);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_blackJackns__playResponse = soap_get_blackJackns__playResponse(soap, NULL, "", NULL);
	if (!soap_tmp_blackJackns__playResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (code && soap_tmp_blackJackns__playResponse->code)
		*code = *soap_tmp_blackJackns__playResponse->code;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
